kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spectral-push
  namespace: openshift
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: spectral-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
